# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: c37d514f663d730fef90402582eb2d41888555f5093627e8dcad5cc0ceb3848786019d26d2f8e0ae2a59ac85c52fab43489218c072d6f85cecd35d7269be78de

test:
  secret_key_base: 2daddf685b45906c5f8de1de1677083215339219d7448d91d261d498f1813ed4c21f7e9e56f92aca8d9628550a2850bcb13d82417dc5e0c125b4cd09c9d9bce7

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
