# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: d6349256da7f91d666c5f2ba0cc77ee86b817ab281e86342807541497adc146eb2beb160bba7a1b56d2d23a3ce64ba9ce8cbaa312879c734004e0f1d3444b1ef

test:
  secret_key_base: 9b005a049bc44acf85487245cf203039e80c959319d6951066b45bb76211d9e921abdcac307df7d8279c00f0d72207b104d5a9d2e5537b8f2d7adc1b93fa6444

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
